### ISSUE TITLE
migrate to trpc v10

### ISSUE THREAD

**Issue by dai-shi** [jotai-labs/jotai-trpc#4]
when will v10 be released?

**Comment by dai-shi** [comment]
https://github.com/jotai-labs/jotai-trpc/pull/1#discussion_r956058799
@sachinraja Is non-proxy API for libraries ready?

**Comment by sachinraja** [comment]
Unsure, I forgot to bring it up before. Will probably get back to you by tomorrow on that.

**Comment by sachinraja** [comment]
We're going to have a separate client where all the arguments are unknown instead of strictly typed. For now though, you can use the deprecated API in `createTRPCClient`.
